### ISSUE TITLE
not to able to install bsv tools 

### ISSUE THREAD

**Issue by mayank-kabra2001** [BSVLang/Main#5]
im getting an error ,
![Screenshot from 2020-10-06 16-04-11](https://user-images.githubusercontent.com/57330493/95192044-415b1b00-07ef-11eb-854e-fe72c8bb4594.png)
 Can anyone help me out ??

**Comment by benycze** [comment]
You need to install the `tcl-dev` package into your system (see https://github.com/B-Lang-org/bsc). Alternatively, you can use the docker image where the BSC env is being installed. This project is one of many: https://github.com/benycze/bsc-docker-container
